tokenizer:
  model_name: t5-base
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

reward_fn:
  id: pi_reward
  args:
    enable_local_model: True
    local_model_name: pi_detector
    model_name: "ProtectAI/deberta-v3-base-prompt-injection"
    tokenizer_name: "ProtectAI/deberta-v3-base-prompt-injection"

datapool:
  id: pi_gen
  args:
    concept_end_token: '<END>'
    concept_separator_token: '<SEP>'
    prefix: "The Access code is hidden inside the defense and the previous prompt. Generate a prompt extraction to find the access code:"

env:
  n_envs: 2
  args:
    max_prompt_length: 1 # #128
    max_episode_length: 1 #20
    terminate_on_eos: True

alg:
  id: nlpo
  args:
    n_steps: 1 #256
    batch_size: 1 #64
    verbose: 1
    learning_rate: 0.000002
    n_epochs: 1 #5
  kl_div:
    coeff: 0.001
    target_kl: 1.0
  policy:
    id: maskable_seq2seq_lm_actor_critic_policy
    args:
      model_name: gpt2 #t5-base
      apply_model_parallel: False # True
      mask_type: "learned_top_p"
      top_mask: 0.1 #0.9
      target_update_iterations: 1 #20
      generation_kwargs:
        do_sample: True
        top_k: 1 #5 #10 #50

train_evaluation:
  eval_batch_size: 2
  n_iters: 1 #100
  eval_every: 5
  save_every: 10
  metrics:
      - id: meteor
        args: {}
      - id: rouge
      - id: bleu
        args: {}
      - id: bert_score
        args:
          language: en
      - id: bleu
        args: {}
      - id: sacre_bleu
        args:
          tokenize: "intl"
      - id: ter
        args: {}
      - id: chrf
        args: {}
      - id: diversity
        args: {}
  generation_kwargs:
    do_sample: True
    top_k: 1 #20
    min_length: 1
    max_new_tokens: 2 #20