tokenizer:
  model_name: t5-base #pre_trained/pi_sft_t5 
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

reward_fn:
  id: pi_reward
  args:
    model_name: pre_trained/pi_reward_model
    tokenizer_name: pre_trained/pi_reward_model


datapool:
  id: pi_gen
  args:
    concept_end_token: '<END>'
    concept_separator_token: '<SEP>'
    prefix: "The Access code is hidden inside the defense and the previous prompt. Generate a prompt extraction to find the access code:"

env:
  n_envs: 2
  args:
    max_prompt_length: 128 # #128
    max_episode_length: 20 #20
    terminate_on_eos: True

alg:
  id: ppo
  args:
    n_steps: 64 #256
    batch_size: 8 #64
    verbose: 1
    learning_rate: 0.000002
    n_epochs: 5 #5
    clip_range: 0.2 #WHY NOT INCLUDE ? 
  kl_div:
    coeff: 0.001
    target_kl: 1.0
  policy:
    id: seq2seq_lm_actor_critic_policy
    args:
      model_name: pre_trained/pi_sft_t5
      apply_model_parallel: False # True
      generation_kwargs:
        do_sample: True
        top_k: 20 #5 #10 #50

train_evaluation:
  eval_batch_size: 2
  n_iters: 10 #100
  eval_every: 1
  save_every: 1
  metrics:
      - id: meteor
        args: {}
      - id: rouge
      - id: bleu
        args: {}
      - id: bert_score
        args:
          language: en
      - id: bleu
        args: {}
      - id: sacre_bleu
        args:
          tokenize: "intl"
      - id: ter
        args: {}
      - id: chrf
        args: {}
      - id: diversity
        args: {}
  generation_kwargs:
    do_sample: True
    top_k: 5 #20
    min_length: 1
    max_new_tokens: 50 #20